-- 2022년 1월의 도서 판매 데이터를 기준  저자 별, 카테고리 별 매출액
-- 저자 ID를 오름차순, 카테고리를 내림차순 정렬

# SELECT 
#     D.AUTHOR_ID,
#     D.AUTHOR_NAME,
#     D.CATEGORY,
#     (D.PRICE * SUM(C.SALES))AS TOTAL_SALES
# FROM BOOK_SALES C
# JOIN 
#     (SELECT
#         A.BOOK_ID,
#         A.AUTHOR_ID,
#         B.AUTHOR_NAME,
#         A.CATEGORY,
#         A.PRICE
#     FROM BOOK A 
#     INNER JOIN AUTHOR B
#         ON A.AUTHOR_ID = B.AUTHOR_ID) D
#     ON C.BOOK_ID = D.BOOK_ID
# GROUP BY D.AUTHOR_ID
# ORDER BY D.AUTHOR_ID, D.CATEGORY;


SELECT
    A.AUTHOR_ID,
    B.AUTHOR_NAME,
    A.CATEGORY,
    SUM(A.PRICE * C.SALES)AS TOTAL_SALES
FROM
    BOOK A
LEFT OUTER JOIN AUTHOR B ON
    A.AUTHOR_ID = B.AUTHOR_ID
LEFT OUTER JOIN BOOK_SALES C ON
    A.BOOK_ID = C.BOOK_ID AND
    SALES_DATE LIKE '2022-01%'
GROUP BY
    A.AUTHOR_ID,
    A.CATEGORY
ORDER BY
    A.AUTHOR_ID,
    A.CATEGORY DESC;